Select
	SITE.SITE_NAME As Company,
	RMA.ID As RMANum,
	RMA.CREATE_DATE As RMADate,
	CUSTOMER.NAME As CustName,
	IsNull(CUSTOMER_ORDER.CONTACT_FIRST_NAME + ' ','') + IsNull(CUSTOMER_ORDER.CONTACT_LAST_NAME,'') AS ContactName,
	--ALL LINE INFO
	RMA_LINE.LINE_NO As RMALine,
	RMA.ORG_CUST_ORDER_ID As OrderNum,
	RMA_LINE.ORG_ORDER_LINE_NO As OrderLine,
	'' As OrderRelNum,
	CUST_ORDER_LINE.PART_ID As PartNum,
	IsNull(CUST_ORDER_LINE.DRAWING_REV_NO,'') As RevNum,
	CUST_ORDER_LINE.MISC_REFERENCE As LineDesc,
	RMA_LINE.QTY As ReturnQty,
	'' As ReasonDesc
FROM RMA with (nolock)
	INNER JOIN SITE	with (nolock) ON RMA.SITE_ID = SITE.ID
	INNER JOIN CUSTOMER_ORDER with (nolock) ON RMA.ORG_CUST_ORDER_ID = CUSTOMER_ORDER.ID
	INNER JOIN CUSTOMER with (nolock) ON CUSTOMER_ORDER.CUSTOMER_ID = CUSTOMER.ID
	LEFT OUTER JOIN RMA_LINE with (nolock) ON RMA.ID = RMA_LINE.RMA_ID
	LEFT OUTER JOIN CUST_ORDER_LINE with (nolock) ON CUSTOMER_ORDER.ID = CUST_ORDER_LINE.CUST_ORDER_ID AND RMA_LINE.ORG_ORDER_LINE_NO = CUST_ORDER_LINE.LINE_NO
WHERE 
	RMA.CREATE_DATE >= '{StartDate}' AND RMA.CREATE_DATE <= '{EndDate}'
	--AND CUSTOMER_ORDER.ID = '{CustID}'
ORDER BY 
	RMA.CREATE_DATE Desc