Select TOP 100
	CUSTOMER_ORDER.ID As OrderNum,
	CUSTOMER_ORDER.ORDER_DATE As OrderDate,
	CUSTOMER_ORDER.CUSTOMER_PO_REF As PoNum,
	CUSTOMER_ORDER.TOTAL_AMT_ORDERED As OrderAmt,
	Case CUSTOMER_ORDER.STATUS When 'R' Then 1 Else 0 End As OpenOrder,
	CUSTOMER_ORDER.CUSTOMER_ID As CustID,
	CUSTOMER.NAME As CustName,
	CUST_ORDER_LINE.LINE_NO As OrderLine,
	CUST_ORDER_LINE.PART_ID As PartNum,
	PART.DESCRIPTION As PartDesc,
	CUST_ORDER_LINE.UNIT_PRICE As UnitPrice,
	CUST_ORDER_LINE.USER_ORDER_QTY * CUST_ORDER_LINE.UNIT_PRICE As ExtPrice,
	CUST_ORDER_LINE.USER_ORDER_QTY As OrderQty,
	CUST_ORDER_LINE.TOTAL_USR_SHIP_QTY As ShippedQty
From 
	CUSTOMER_ORDER with (nolock)
	INNER JOIN CUSTOMER with (nolock) ON CUSTOMER_ORDER.CUSTOMER_ID = CUSTOMER.ID
	INNER JOIN CUST_ORDER_LINE with (nolock) ON CUSTOMER_ORDER.ID = CUST_ORDER_LINE.CUST_ORDER_ID
	LEFT OUTER JOIN PART with (nolock) ON CUST_ORDER_LINE.PART_ID = PART.ID
WHERE 
	CUSTOMER_ORDER.ORDER_DATE >= '{StartDate}' AND CUSTOMER_ORDER.ORDER_DATE <= '{EndDate}'
ORDER BY 
	CUSTOMER_ORDER.ORDER_DATE Desc