SELECT
	SUM(R.TOTAL_AMOUNT) AS Sales
	, CAST(YEAR(R.INVOICE_DATE) AS VARCHAR) as InvcYear
	, C.TERRITORY AS Territory
FROM
	RECEIVABLE R with(nolock)

	INNER JOIN CUSTOMER C with(nolock) ON
	C.ID = R.CUSTOMER_ID
WHERE
	DATEDIFF(MONTH, R.INVOICE_DATE, GETDATE()) = 1
	OR (DATEDIFF(MONTH, R.INVOICE_DATE, GETDATE()) = 12
	AND DAY(R.INVOICE_DATE) <= DAY(GETDATE()))
GROUP BY
	YEAR(R.INVOICE_DATE)
	, C.TERRITORY